--- 
abstract: HTML::Parser With Stacked Handlers
author: 
  - Copyright (c) 2007 Daisuke Maki <daisuke@endeworks.jp>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: HTML-Parser-Stacked
no_index: 
  directory: 
    - inc
    - t
requires: 
  HTML::Parser: 3
version: 0.00001
